framework:
    router:
        # Configure how to generate URLs in non-HTTP contexts, such as CLI commands.
        # See https://symfony.com/doc/current/routing.html#generating-urls-in-commands
        #default_uri: http://localhost
    rate_limiter:
        anonymous:
            policy: 'sliding_window'
            limit: 100
            interval: '15 minutes'

when@prod:
    framework:
        router:
            strict_requirements: null
